# Generated by Django 5.2.1 on 2025-05-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasolina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ganho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('km', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
