# Generated by Django 5.2.1 on 2025-05-17 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uber',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
