# Generated by Django 5.2.1 on 2025-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_uber_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uber',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
