# Generated by Django 5.2.1 on 2025-05-17 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_alter_uber_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='uber',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
