# Generated by Django 5.2.1 on 2025-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_alter_uber_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uber',
            name='data_criacao',
            field=models.DateTimeField(),
        ),
    ]
