# Generated by Django 5.2.1 on 2025-05-17 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0006_alter_uber_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uber',
            name='created_at',
            field=models.DateField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='uber',
            name='data_criacao',
            field=models.DateTimeField(default=False),
        ),
    ]
