# Generated by Django 5.2.1 on 2025-05-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0013_alter_uber_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uber',
            name='ganho',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uber',
            name='gasolina',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uber',
            name='km',
            field=models.FloatField(),
        ),
    ]
